### ISSUE TITLE
could you  share the pictures in your ‘data’ folder? Now I see the ‘txt’ documents just the name of these pictures

### ISSUE THREAD

**Issue by violetsaturn** [leimao/DLSS_ESPCN#1]
hello ,could you share us the pictures in you folder of 'data'? I want to have a try about the net, thank you!

**Comment by leimao** [comment]
Hi,
Please read the README.md document. Due to copyright reasons, I will not disclose the source of data. However, you may collect your own image dataset and try the model. My scripts should be sufficient to preprocess your data, train and test the model. Alternatively, if you happen to know there is a game dataset which does not have copyright problems, please also let me know.
